name: metrics-both-final

on:
  workflow_dispatch: {}

jobs:
  both:
    runs-on: windows-latest
    timeout-minutes: 20

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # ---------------- ID path ----------------
      - name: Preflight (ID)
        shell: pwsh
        run: |
          py preflight.py --mode id `
            --top1 ce_top1_final_ID.csv `
            --gold gold_id_unbalanced_nobom.jsonl `
            --out-csv top1_eval_id.csv `
            --out-gold gold_eval_id.jsonl
          if (!(Test-Path top1_eval_id.csv))   { throw "Missing top1_eval_id.csv" }
          if (!(Test-Path gold_eval_id.jsonl)) { throw "Missing gold_eval_id.jsonl" }

      - name: Full metrics (ID)
        shell: pwsh
        run: |
          py metrics_top1.py --top1_csv top1_eval_id.csv `
            --gold_jsonl gold_eval_id.jsonl `
            --out metrics_id.txt
          Get-Content metrics_id.txt

      # --------------- LABEL path --------------
      - name: Build LABEL top1_eval + gold (deterministic)
        shell: pwsh
        run: |
          $rows = Import-Csv .\ce_top1_final_LABEL_metrics.csv
          if (-not $rows) { throw "LABEL CSV has no rows." }

          $out = foreach ($r in $rows) {
            [pscustomobject]@{
              q          = $r.query
              d          = $r.candidate
              p_relevant = $r.p_relevant
            }
          }

          $out | Export-Csv -NoTypeInformation .\top1_eval_label.csv
          if (!(Test-Path top1_eval_label.csv)) { throw "Missing top1_eval_label.csv" }

          Copy-Item .\gold_label_unbalanced_nobom.jsonl .\gold_eval_label.jsonl -Force
          if (!(Test-Path gold_eval_label.jsonl)) { throw "Missing gold_eval_label.jsonl" }

      - name: Full metrics (LABEL)
        shell: pwsh
        run: |
          py metrics_top1.py --top1_csv top1_eval_label.csv `
            --gold_jsonl gold_eval_label.jsonl `
            --out metrics_label.txt
          Get-Content metrics_label.txt

      # --------------- Summary -----------------
      - name: Summary (ID vs LABEL)
        shell: pwsh
        run: |
          function Get-P1([string]$path){
            $t = Get-Content $path -Raw
            $m = [regex]::Match($t,'P@1 \(overall\):\s*([0-9.]+)')
            if(-not $m.Success){ return "NA" }
            return $m.Groups[1].Value
          }
          $p1_id    = Get-P1 "metrics_id.txt"
          $p1_label = Get-P1 "metrics_label.txt"
          "ID P@1    = $p1_id"    | Out-File both_summary.txt
          "LABEL P@1 = $p1_label" | Out-File both_summary.txt -Append
          Get-Content both_summary.txt

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: both-artifacts
          path: |
            top1_eval_id.csv
            gold_eval_id.jsonl
            metrics_id.txt
            top1_eval_label.csv
            gold_eval_label.jsonl
            metrics_label.txt
            both_summary.txt

