name: metrics-id-final

on:
  workflow_dispatch: {}
  

jobs:
  id-final:
    runs-on: windows-latest
    timeout-minutes: 20

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # 1) Preflight: normalize and build eval inputs
      - name: Preflight (ID mode)
        shell: pwsh
        run: |
          py preflight.py --mode id `
            --top1 ce_top1_final_ID.csv `
            --gold gold_id_unbalanced_nobom.jsonl `
            --out-csv top1_eval.csv `
            --out-gold gold_eval.jsonl

      # 2) Deterministic micro sample (n=200) in pure PowerShell
      - name: Make deterministic micro sample (n=200)
        shell: pwsh
        run: |
          $goldMap = @{}
          Get-Content gold_eval.jsonl | ForEach-Object {
            if ($_ -and $_.Trim()) {
              $o = $_ | ConvertFrom-Json
              if ($o.query) { $goldMap[$o.query.Trim()] = 1 }
            }
          }
          $rows = Import-Csv top1_eval.csv
          # Deterministic order: take first 200 rows whose query exists in gold
          $sel = $rows | Where-Object { $goldMap.ContainsKey(($_.query)) } | Select-Object -First 200
          $sel | Export-Csv -NoTypeInformation sample200_eval.csv
          Write-Host "Wrote sample200_eval.csv with $($sel.Count) rows"

      # 3) Micro-eval (warn-only; never blocks the full run)
      - name: Micro-eval (warn-only)
        shell: pwsh
        run: |
          py metrics_top1.py --top1_csv sample200_eval.csv `
                             --gold_jsonl gold_eval.jsonl `
                             --out micro_metrics.txt
          $t = Get-Content micro_metrics.txt -Raw
          $m = [regex]::Match($t,'P@1 \(overall\):\s*([0-9.]+)')
          if($m.Success){
            $p = [double]$m.Groups[1].Value
            if($p -lt 0.05){ Write-Host "::warning::Micro P@1 $p < 0.05 (threshold 0.05)"; }
            else { Write-Host "Micro P@1 OK: $p"; }
          } else {
            Write-Host "::warning::Could not parse micro metrics"
          }

      # 4) Full eval on canonical files (authoritative result)
      - name: Full metrics (ID)
        shell: pwsh
        run: |
          py metrics_top1.py --top1_csv top1_eval.csv `
                             --gold_jsonl gold_eval.jsonl `
                             --out metrics_unbalanced_p1_id_final.txt
          Get-Content metrics_unbalanced_p1_id_final.txt

      # 5) Misses report (Top 40)
      - name: Misses Top 40
        shell: pwsh
        run: |
          py misses_report.py --top1_csv top1_eval.csv `
                              --gold_jsonl gold_eval.jsonl `
                              --out_csv debug_misses_top40.csv `
                              --k 40 `
                              --p_col p_relevant `
                              --pirr_col p_irrelevant

      # 6) Upload artifacts
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: id-final-artifacts
          path: |
            sample200_eval.csv
            top1_eval.csv
            gold_eval.jsonl
            micro_metrics.txt
            metrics_unbalanced_p1_id_final.txt
            debug_misses_top40.csv
